---
default: &default
  adapter: mysql2
  host: localhost
  username: root
  password:
  encoding: utf8mb4

development: &development
  <<: *default
  database: myapp_development

development_w:
  <<: *development

development_r:
  <<: *development

test: &test
  <<: *default
  database: myapp_test

test_w:
  <<: *test

test_r:
  <<: *test

production:
